services:

  db:
    image: postgres:17-alpine
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: Password123!
      POSTGRES_DB: PotPalDb
    ports:
      - "5432:5432"
    volumes:
      - "./data:/var/lib/postgresql/data/"


  backend:
    container_name: backend
    restart: unless-stopped
    build: ./Backend
    ports:
      - "6002:5000" # Optional for debugging
    #environment:
     # - DB_CONNECTION_STRING=Host=10.133.51.109;Port=5432;Database=PotPalDb;Username=user;Password=Password123!;
      #- DB_CONNECTION_STRING=server=db;database=${PG_DATABASE};port=5432;user=${PG_USER};password=${PG_PASSWORD};
      #- SMTP_CONNECTION_STRING=${SMTP_ADDRESS}__${SMTP_PORT}__${SMTP_USER}__${SMTP_PASSWORD}


  frontend:
    container_name: frontend
    restart: unless-stopped
    build: ./Frontend
    ports:
      - "6001:5000"

  
  nginx:
    image: nginx
    container_name: nginx
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./Nginx/nginx.conf:/etc/nginx/conf.d/default.conf

    depends_on:
      - backend
      - frontend

     