# maintainer info
FROM mcr.microsoft.com/dotnet/sdk:9.0@sha256:3fcf6f1e809c0553f9feb222369f58749af314af6f063f389cbd2f913b4ad556 AS build
WORKDIR /App

# build project
WORKDIR /app
COPY ./app /app
RUN mkdir /build
RUN dotnet publish --sc -o /build

ENV ASPNETCORE_URLS=http://+:5000

# Run project
WORKDIR /build
CMD ["/build/app"]