# maintainer info
FROM mcr.microsoft.com/dotnet/sdk:9.0 AS build

ENV ASPNETCORE_URLS=http://+:5000

WORKDIR /app
COPY  ./ /app
RUN mkdir /build
RUN dotnet publish --sc -o /build

# Run project
WORKDIR /build
CMD ["/build/Backend"]